### ISSUE TITLE
First Steps - Init 

### ISSUE THREAD

**Issue by dev0Guy** [dev0Guy/Oran-TrafficManagement#1]
-  [x] db- create database, run and visualise json file.
-  [x] create simple custome env for rllib 
-  [x] create simple custome model for rllib

**Comment by Amit-Nadam** [comment]
[DONE] db- create database, run and visualise json file. (with @dev0Guy)

**Comment by dev0Guy** [comment]
[DONE]  Create simple custom env for rllib 
[NEED] decide on reward function (different in the queue is week), avg wait time is not good

**Comment by dev0Guy** [comment]
[DONE] decide on reward function (different in the queue is week), avg wait time is not good
USED: Traffic Signal Control via Reinforcement Learning for Reducing
Global Vehicle Emission PAPER

**Comment by dev0Guy** [comment]
[DONE] Create simple custom model for rllib (with @Amit-Nadam )

**Comment by dev0Guy** [comment]
[Done] create a simple custome model for rllib (with @Amit-Nadam )
